//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: process_monitor.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// The service definition.
///
/// Usage: instantiate `Processmonitor_ProcessMonitorClient`, then call methods of this protocol to make API calls.
internal protocol Processmonitor_ProcessMonitorClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol? { get }

  func getProcesses(
    _ request: Processmonitor_ProcessRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Processmonitor_ProcessRequest, Processmonitor_ProcessResponse>
}

extension Processmonitor_ProcessMonitorClientProtocol {
  internal var serviceName: String {
    return "processmonitor.ProcessMonitor"
  }

  /// Unary call to GetProcesses
  ///
  /// - Parameters:
  ///   - request: Request to send to GetProcesses.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getProcesses(
    _ request: Processmonitor_ProcessRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Processmonitor_ProcessRequest, Processmonitor_ProcessResponse> {
    return self.makeUnaryCall(
      path: Processmonitor_ProcessMonitorClientMetadata.Methods.getProcesses.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProcessesInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Processmonitor_ProcessMonitorClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Processmonitor_ProcessMonitorNIOClient")
internal final class Processmonitor_ProcessMonitorClient: Processmonitor_ProcessMonitorClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the processmonitor.ProcessMonitor service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Processmonitor_ProcessMonitorNIOClient: Processmonitor_ProcessMonitorClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol?

  /// Creates a client for the processmonitor.ProcessMonitor service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// The service definition.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Processmonitor_ProcessMonitorAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol? { get }

  func makeGetProcessesCall(
    _ request: Processmonitor_ProcessRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Processmonitor_ProcessRequest, Processmonitor_ProcessResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Processmonitor_ProcessMonitorAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Processmonitor_ProcessMonitorClientMetadata.serviceDescriptor
  }

  internal var interceptors: Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetProcessesCall(
    _ request: Processmonitor_ProcessRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Processmonitor_ProcessRequest, Processmonitor_ProcessResponse> {
    return self.makeAsyncUnaryCall(
      path: Processmonitor_ProcessMonitorClientMetadata.Methods.getProcesses.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProcessesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Processmonitor_ProcessMonitorAsyncClientProtocol {
  internal func getProcesses(
    _ request: Processmonitor_ProcessRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Processmonitor_ProcessResponse {
    return try await self.performAsyncUnaryCall(
      path: Processmonitor_ProcessMonitorClientMetadata.Methods.getProcesses.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProcessesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Processmonitor_ProcessMonitorAsyncClient: Processmonitor_ProcessMonitorAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Processmonitor_ProcessMonitorClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getProcesses'.
  func makeGetProcessesInterceptors() -> [ClientInterceptor<Processmonitor_ProcessRequest, Processmonitor_ProcessResponse>]
}

internal enum Processmonitor_ProcessMonitorClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ProcessMonitor",
    fullName: "processmonitor.ProcessMonitor",
    methods: [
      Processmonitor_ProcessMonitorClientMetadata.Methods.getProcesses,
    ]
  )

  internal enum Methods {
    internal static let getProcesses = GRPCMethodDescriptor(
      name: "GetProcesses",
      path: "/processmonitor.ProcessMonitor/GetProcesses",
      type: GRPCCallType.unary
    )
  }
}

/// The service definition.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Processmonitor_ProcessMonitorProvider: CallHandlerProvider {
  var interceptors: Processmonitor_ProcessMonitorServerInterceptorFactoryProtocol? { get }

  func getProcesses(request: Processmonitor_ProcessRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Processmonitor_ProcessResponse>
}

extension Processmonitor_ProcessMonitorProvider {
  internal var serviceName: Substring {
    return Processmonitor_ProcessMonitorServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetProcesses":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Processmonitor_ProcessRequest>(),
        responseSerializer: ProtobufSerializer<Processmonitor_ProcessResponse>(),
        interceptors: self.interceptors?.makeGetProcessesInterceptors() ?? [],
        userFunction: self.getProcesses(request:context:)
      )

    default:
      return nil
    }
  }
}

/// The service definition.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Processmonitor_ProcessMonitorAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Processmonitor_ProcessMonitorServerInterceptorFactoryProtocol? { get }

  func getProcesses(
    request: Processmonitor_ProcessRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Processmonitor_ProcessResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Processmonitor_ProcessMonitorAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Processmonitor_ProcessMonitorServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Processmonitor_ProcessMonitorServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Processmonitor_ProcessMonitorServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetProcesses":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Processmonitor_ProcessRequest>(),
        responseSerializer: ProtobufSerializer<Processmonitor_ProcessResponse>(),
        interceptors: self.interceptors?.makeGetProcessesInterceptors() ?? [],
        wrapping: { try await self.getProcesses(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Processmonitor_ProcessMonitorServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'getProcesses'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetProcessesInterceptors() -> [ServerInterceptor<Processmonitor_ProcessRequest, Processmonitor_ProcessResponse>]
}

internal enum Processmonitor_ProcessMonitorServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ProcessMonitor",
    fullName: "processmonitor.ProcessMonitor",
    methods: [
      Processmonitor_ProcessMonitorServerMetadata.Methods.getProcesses,
    ]
  )

  internal enum Methods {
    internal static let getProcesses = GRPCMethodDescriptor(
      name: "GetProcesses",
      path: "/processmonitor.ProcessMonitor/GetProcesses",
      type: GRPCCallType.unary
    )
  }
}
